# =============================================================================
# TCL Build Template Reference
# =============================================================================
# This file is a reference for the TCL script generated by `vam build`.
# The actual build.tcl is auto-generated in your project's build/ directory.
#
# Variables filled from fpga.yml:
#   {{PART}}        - FPGA part number (e.g., xc7a35ticsg324-1L)
#   {{TOP}}         - Top module name
#   {{SOURCES}}     - read_verilog / read_vhdl commands
#   {{CONSTRAINTS}} - read_xdc commands
# =============================================================================

set part "{{PART}}"
set top "{{TOP}}"
set outDir "/workspace/build"

file mkdir $outDir

# Read sources
{{SOURCES}}

# Read constraints
{{CONSTRAINTS}}

# Synthesis
puts "==> Starting synthesis..."
synth_design -top $top -part $part
write_checkpoint -force $outDir/post_synth.dcp
report_utilization -file $outDir/utilization.rpt
puts "==> Synthesis complete."

# Implementation
puts "==> Starting implementation..."
opt_design
place_design
phys_opt_design
route_design
write_checkpoint -force $outDir/post_route.dcp
puts "==> Implementation complete."

# Reports
report_timing_summary -file $outDir/timing.rpt
report_power -file $outDir/power.rpt

# Generate bitstream
puts "==> Generating bitstream..."
write_bitstream -force $outDir/${top}.bit
puts "==> Done! Bitstream: $outDir/${top}.bit"
